### ISSUE TITLE
Missing data?

### ISSUE THREAD

**Issue by shaze** [Deutsche-Boerse/dbg-pds#4]
Apologies if I am I am doing something stupied but I can see any data in these public data sets.

If I say: aws s3 --region eu-west-2 ls  s3://deutsche-boerse-xetra-pds/ then I get a long list of directories for each data , but the individual directories seem empty

e.g. aws s3 --region eu-west-2 ls  s3://deutsche-boerse-xetra-pds/2018-04-01

With the other bucket, deutsche-boerse-eurex-pds, there are lots of files but they only contain one line -- the header

For example, if I try http://deutsche-boerse-eurex-pds.s3.amazonaws.com/2018-03-24/2018-03-24_BINS_XEUR00.csv

Thanks

Scott

**Comment by slock-dbs** [comment]
Hi Scott,

I'm sorry for the delay in replying!

The dates you've cited there are non-trading days (Sundays), for which we don't generate any data.

There is an inconsistency in the way we handle empty days for historical data and the way we handle it for newly loaded data.  For more recent data, we generate a header-only CSV as a positive indication that there really is no data available, but for older data we didn't do that.

I've got a backlogged task to fix the inconsistency.

We have a glitch with the Eurex pipeline and it's not delivering data at the moment, so the Eurex data is... sparse... but that should be fixed by May 1st.

Cheers,
Steve.

**Comment by shaze** [comment]
Thanks  for the response!
